### ISSUE TITLE
[dglo on 2017-08-17 15:04:21] : HitSpool: HsWorker dies because it cannot create remote directory on 2ndbuild

### ISSUE THREAD

**Issue by dglo** [WIPACrepo/hitspool#18]
[master 0362cd7] 1 changed, 1 inserted, 1 deleted

**Comment by dglo** [comment]
[dglo on 2017-09-01 13:58:29]
2017-09-01 08:01:37 ERROR Cannot process request "WorkerRequest(username='unknown', request_id='59a913cf000069', host='2ndbuild', stop_ticks=210240488324390000, start_ticks=210240478324390000, prefix='HESE', version=2, msgtype='REQUEST', copy_dir=None, hubs=None, destination_dir='/mnt/data/hese_hs/129956_56896338_2017-09-01T08:00:48.332439', extract=True)"
Traceback (most recent call last):
  File "/mnt/data/pdaqlocal/HsInterface/current/HsWorker.py", line 205, in mainloop
    update_status=update_status)
  File "/mnt/data/pdaqlocal/HsInterface/current/HsWorker.py", line 130, in alert_parser
    make_remote_dir=False)
  File "/mnt/data/pdaqlocal/HsInterface/current/HsRSyncFiles.py", line 503, in request_parser
    make_remote_dir=make_remote_dir)
  File "/mnt/data/pdaqlocal/HsInterface/current/HsRSyncFiles.py", line 180, in __copy_and_send
    bwlimit=self.BWLIMIT, log_format="%i%n%L")
  File "/mnt/data/pdaqlocal/HsInterface/current/HsRSyncFiles.py", line 533, in send_files
    log_format=log_format, relative=relative)
  File "/mnt/data/pdaqlocal/HsInterface/current/HsCopier.py", line 341, in __init__
    make_remote_dir=make_remote_dir)
  File "/mnt/data/pdaqlocal/HsInterface/current/HsCopier.py", line 26, in __init__
    self.make_remote_directory(rmt_user, rmt_host, rmt_dir)
  File "/mnt/data/pdaqlocal/HsInterface/current/HsCopier.py", line 113, in make_remote_directory
    raise HsException("Cannot create %s:%s" % (rstr, rmt_dir))
HsException: Cannot create pdaq@2ndbuild:/mnt/data/pdaqlocal/HsDataCopy/HESE_20170901_080047_ichub15

**Comment by dglo** [comment]
[dglo on 2017-09-01 15:21:08]
svn commit -m"Issue 8219: Retry remote 'mkdir -p' a couple of times before giving up" HsCopier.py
Sending        HsCopier.py
Transmitting file data .done
Committing transaction...
[commit 24389d4683958ec27ed52e6cbf2f3c18c000a36d] Committed revision 16698.
